services:
  web:
    build:
      context: .
      # 传递构建参数
      args:
        - APP_ENV=dev
    image: nextdoor-home-dev:latest
    container_name: nextdoor-home-dev
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - TZ=Asia/Shanghai
    security_opt:
      - no-new-privileges:true

